package frc.robot.dashboard;

public record DashboardSnapshot(
        double timestampSec,
        String robotMode,
        boolean enabled,
        String alliance,
        double matchTimeSec,
        double poseX_m,
        double poseY_m,
        double headingDeg,
        // Raw Pigeon2 IMU telemetry
        double pigeonYawDeg,
        double pigeonPitchDeg,
        double pigeonRollDeg,
        double shooterLeftRps,
        double shooterRightRps,
        boolean shooterAtSpeed,
        boolean intakeHomed,
        boolean intakeLimitSwitchPressed,
        double intakeTiltDeg,
        double intakeRollerCurrentAmps,
        double feederCurrentAmps,
        double hopperCurrentAmps,
        boolean climberArmed,
        double climberPositionRot,
        double climberCurrentAmps,
        String alignState,
        boolean alignCommandActive,
        boolean alignHasTarget,
        boolean alignGeometryFeasible,
        boolean alignHasShootableTarget,
        double alignYawDeg,
        double alignAimErrorDeg,
        double alignLeadYawDeg,
        double alignPitchDeg,
        double alignTargetRps,
        double alignRadialVelocityMps,
        double alignLateralVelocityMps,
        double alignCommandedXVelocityMps,
        double alignCommandedYVelocityMps,
        double alignTranslationCapMps,
        double alignTimeOfFlightSec,
        boolean alignFeedGateReady,
        String alignAbortReason,
        boolean readyToScore,
        String readyReason,
        // 2026 REBUILT: HUB shift activity
        boolean hubActive,
        double hubSecondsToNextShift,
        // System health
        double batteryVoltage,
        boolean brownoutAlert,
        boolean isBrownout,
        // Auto selection & execution
        String selectedAutoName,
        String selectedAutoSource,
        String[] autoOptions,
        boolean autoCommandRunning,
        // Expected auto starting pose (blue-side coordinates; NaN = no starting pose)
        double autoStartX_m,
        double autoStartY_m,
        double autoStartHeadingDeg,
        // Match info
        long matchNumber,
        String eventName,
        // Camera / vision connection
        boolean cameraConnected,
        String cameraStatus,
        int cameraActiveDeviceId,
        String cameraActiveName,
        String cameraActivePath,
        String cameraEnumerated,
        String cameraLastError,
        long cameraFrameCount,
        double cameraLastFrameTimestampSec,
        // Vision tag detection (from background vision thread)
        int visionTagId,
        boolean visionHasTarget,
        double visionYawDeg,
        double visionPitchDeg,
        double visionBestTagYawDeg,
        double visionBestTagPitchDeg,
        double visionDistanceM,
        double visionTagPixelHeightPx,
        int visionHubTagCount,
        int visionHubFaceCount,
        double visionHubSpanPx,
        double visionTargetTimestampSec,
        // CAN bus health
        double canBusUtilization,
        long canReceiveErrorCount,
        long canTransmitErrorCount,
        // Swerve module angles (FL, FR, BL, BR)
        double swerveFLAngleDeg,
        double swerveFRAngleDeg,
        double swerveBLAngleDeg,
        double swerveBRAngleDeg,
        // CANCoder health (per-module)
        double cancoderFLPosRot,
        double cancoderFRPosRot,
        double cancoderBLPosRot,
        double cancoderBRPosRot,
        double cancoderFLAbsRawRot,
        double cancoderFRAbsRawRot,
        double cancoderBLAbsRawRot,
        double cancoderBRAbsRawRot,
        boolean cancoderFLOk,
        boolean cancoderFROk,
        boolean cancoderBLOk,
        boolean cancoderBROk,
        // Motor temperatures (Celsius)
        double driveFLTempC,
        double driveFRTempC,
        double driveBLTempC,
        double driveBRTempC,
        double shooterLeftTempC,
        double shooterRightTempC,
        // Controller diagnostics
        String driverButtonsActive,
        String operatorButtonsActive,
        long controlEventSeq,
        double controlEventTimestampSec,
        String controlEventMessage,
        boolean swerveValidationActive,
        String swerveValidationModuleToken,
        String swerveValidationModuleDisplayName,
        String swerveValidationModeToken,
        String swerveValidationModeDisplayName,
        double swerveValidationDrivePercent,
        double swerveValidationSteerPercent,
        double swerveValidationStartAngleDeg,
        double swerveValidationAngleDeltaDeg,
        double swerveValidationStartCANcoderRot,
        double swerveValidationCANcoderDeltaRot) {
}
