package frc.dashboard;

public record DashboardData(
        boolean connected,
        String mode,
        boolean enabled,
        String alliance,
        double matchTimeSec,
        double robotTimestampSec,
        double poseX_m,
        double poseY_m,
        double headingDeg,
        // Raw Pigeon2 IMU telemetry
        double pigeonYawDeg,
        double pigeonPitchDeg,
        double pigeonRollDeg,
        double shooterLeftRps,
        double shooterRightRps,
        boolean shooterAtSpeed,
        boolean intakeHomed,
        boolean intakeLimitSwitchPressed,
        double intakeTiltDeg,
        double intakeRollerCurrentAmps,
        double feederCurrentAmps,
        double hopperCurrentAmps,
        boolean climberArmed,
        double climberPositionRot,
        double climberCurrentAmps,
        String alignState,
        boolean alignCommandActive,
        boolean alignHasTarget,
        boolean alignGeometryFeasible,
        boolean alignHasShootableTarget,
        double alignYawDeg,
        double alignPitchDeg,
        String alignAbortReason,
        boolean readyToScore,
        String readyReason,
        // System health
        double batteryVoltage,
        boolean brownoutAlert,
        boolean isBrownout,
        // Auto selection & execution
        String selectedAutoName,
        boolean autoCommandRunning,
        // Match info
        long matchNumber,
        String eventName,
        // Camera / vision connection
        boolean cameraConnected,
        // CAN bus health
        double canBusUtilization,
        long canReceiveErrorCount,
        long canTransmitErrorCount,
        // Swerve module angles
        double swerveFLAngleDeg,
        double swerveFRAngleDeg,
        double swerveBLAngleDeg,
        double swerveBRAngleDeg,
        // CANcoder calibration telemetry
        double cancoderFLRawRot,
        double cancoderFRRawRot,
        double cancoderBLRawRot,
        double cancoderBRRawRot,
        double cancoderFLOffsetRot,
        double cancoderFROffsetRot,
        double cancoderBLOffsetRot,
        double cancoderBROffsetRot,
        // Motor temperatures
        double driveFLTempC,
        double driveFRTempC,
        double driveBLTempC,
        double driveBRTempC,
        double shooterLeftTempC,
        double shooterRightTempC,
        // Ack (keep at end)
        String ackLastCommand,
        String ackStatus,
        long ackSeq,
        String ackMessage,
        double ackTimestampSec) {
}
