package frc.dashboard;

public record DashboardData(
        boolean connected,
        String mode,
        boolean enabled,
        String alliance,
        double matchTimeSec,
        double poseX_m,
        double poseY_m,
        double headingDeg,
        double shooterLeftRps,
        double shooterRightRps,
        boolean shooterAtSpeed,
        boolean intakeHomed,
        boolean intakeLimitSwitchPressed,
        double intakeTiltDeg,
        double intakeRollerCurrentAmps,
        double feederCurrentAmps,
        double hopperCurrentAmps,
        boolean climberArmed,
        double climberPositionRot,
        double climberCurrentAmps,
        String alignState,
        boolean alignCommandActive,
        boolean alignHasTarget,
        boolean alignGeometryFeasible,
        boolean alignHasShootableTarget,
        double alignYawDeg,
        double alignPitchDeg,
        String alignAbortReason,
        boolean readyToScore,
        String readyReason,
        String ackLastCommand,
        String ackStatus,
        long ackSeq,
        String ackMessage,
        double ackTimestampSec) {
}
